DRAFT: Testing updates
oicr-gsi/mrdetect pull request #4
Opened 2022-11-07 18:24 UTC by alexjfortuna

2022-11-08 16:11 UTC, felixbeaudry commented on README.md
> +`snvDetectionFinalResult`|File?|Final result and call from SNV detection
why did this go to `file?` This is a principle result of the workflow, can it be a mandatory output?

2022-11-08 16:21 UTC, felixbeaudry requested changes
`README.md`: intro to the script L86-97 should probably stay

2022-11-08 16:22 UTC, mlaszloffy approved these changes

2022-11-08 21:50 UTC, gavin-peng approved these changes

2022-11-09 14:44 UTC, felixbeaudry approved these changes

2022-11-09 14:47 UTC, merged